config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#index"
  
  resources :welcome
  resources :firms
  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    has_many :employees_firms
    has_many :firms, through: :employees_firms
    accepts_nested_attributes_for :firms
    
    validates :Ime, :presence => true
    validates :Prezime, :presence => true
    validates :Zanimanje, :presence => true

    
    after_save :flag_trenutnog_posla
    
    def flag_trenutnog_posla
        # Sva radna mesta radnika smrm
        srmr = EmployeesFirm.where(:employee_id => self.id)
        srmr.each do |f|
            f.flag = false
        end
        EmployeesFirm.create(:employee_id => self.id, :firm_id => self.firm_id, :flag => true)
    end

end

app/models/employees_firm.rb
class EmployeesFirm < ActiveRecord::Base
    belongs_to :employee
    belongs_to :firm
    
end

app/models/firm.rb
class Firm < ActiveRecord::Base
    has_many :employees_firms
    has_many :employees, through: :employees_firms
    
    validates :ime_firme, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:Ime, :Prezime, :Zanimanje, :firm_id)
    end
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: [:show, :edit, :update, :destroy]

  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(firm_params)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1
  # PATCH/PUT /firms/1.json
  def update
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: 'Firm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firm_params
      params.require(:firm).permit(:ime_firme)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
  def index
    @employees = Employee.all
  end    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Ime %><br>
    <%= f.text_field :Ime, required: true %>
  </div>
  <div class="field">
    <%= f.label :Prezime %><br>
    <%= f.text_field :Prezime, required: true %>
  </div>
  <div class="field">
    <%= f.label :Zanimanje %><br>
    <%= f.text_field :Zanimanje, required: true %>
  </div>
  <div class="field">
    <%= f.label :firm_id, "Ime Firme" %><br>
    <%= f.collection_select :firm_id, Firm.all, :id, :ime_firme, :include_blank => true %>  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Podešavanja za zaposlenog</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="wrapper">
  <h1>Zaposleni</h1>
  <p id="notice"><%= notice %></p>
  <table class="table">
    <thead>
      <tr class="row header blue">
        <th class="cell">Ime</th>
        <th class="cell">Prezime</th>
        <th class="cell">Zanimanje</th>
        <th class="cell">Ime firme </th>
        <th class="cell" colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @employees.each do |employee| %>
        <tr class="row">
          <td class="cell"><%= employee.Ime %></td>
          <td class="cell"><%= employee.Prezime %></td>
          <td class="cell"><%= employee.Zanimanje %></td>
          <td class="cell"><%= Firm.find_by(:id => employee.employees_firms.last.firm_id).ime_firme unless employee.employees_firms.find_by(:flag => true) == nil %></td>
          <td class="cell"><%= link_to 'Prikaži', employee %></td>
          <td class="cell"><%= link_to 'Promeni', edit_employee_path(employee) %></td>
          <td class="cell"><%= link_to 'Obriši', employee, method: :delete, data: { confirm: 'Da li ste sigurni?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Novi zaposleni', new_employee_path %><br>
  <%= link_to 'Istorija promene firmi zaposlenih', root_path %><br>
  <%= link_to 'Lista firmi', firms_path %> </div>

app/views/employees/new.html.erb
<h1>Novi zaposleni</h1>

<%= render 'form' %>

<%= link_to 'Nazad', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ime:</strong>
  <%= @employee.Ime %>
</p>

<p>
  <strong>Prezime:</strong>
  <%= @employee.Prezime %>
</p>

<p>
  <strong>Zanimanje:</strong>
  <%= @employee.Zanimanje %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/firms/_form.html.erb
<%= form_for(@firm) do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ime_firme %><br>
    <%= f.text_field :ime_firme, required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firms/edit.html.erb
<h1>Editing Firm</h1>

<%= render 'form' %>

<%= link_to 'Show', @firm %> |
<%= link_to 'Back', firms_path %>

app/views/firms/index.html.erb
<div class="wrapper">
  
  <h1>Lista firmi</h1>
  <p id="notice"><%= notice %></p>
  <table class="table">
    <thead>
      <tr class="row header blue">
        <th class="cell">Ime firme</th>
        <th class="cell" colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @firms.each do |firm| %>
        <tr class="row">
          <td class="cell"><%= firm.ime_firme %></td>
          <td class="cell"><%= link_to 'Prikaži', firm %></td>
          <td class="cell"><%= link_to 'Promeni', edit_firm_path(firm) %></td>
          <td class="cell"><%= link_to 'Obriši', firm, method: :delete, data: { confirm: 'Da li ste sigurni?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Nova firma', new_firm_path %><br>
  <%= link_to 'Istorija promene firmi zaposlenih', root_path %><br>
  <%= link_to 'Lista firmi', firms_path %> 
</div>
</div>

app/views/firms/new.html.erb
<h1>Nova firma</h1>

<%= render 'form' %>

<%= link_to 'Back', firms_path %>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ime firme:</strong>
  <%= @firm.ime_firme %>
</p>

<%= link_to 'Edit', edit_firm_path(@firm) %> |
<%= link_to 'Back', firms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="wrapper">
  <h1>Istorija promene firmi zaposlenih</h1>
  <p id="notice"><%= notice %></p>
  <table class="table">
    <thead>
      <tr class="row header blue">
        <th class="cell">Ime</th>
        <th class="cell">Prezime</th>
        <th class="cell">Zanimanje</th>
        <th class="cell">Ime firme </th>
        <th class="cell"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @employees.each do |employee| %>
        <% employee.firms.each do |f| %>
            <tr class="row">
              <td class="cell"><%= employee.Ime %></td>
              <td class="cell"><%= employee.Prezime %></td>
              <td class="cell"><%= employee.Zanimanje %></td>
              <td class="cell"><%= f.ime_firme %></td>
              <td class="cell"><%= link_to 'Prikaži', employee %></td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Novi zaposleni', new_employee_path %><br>
  <%= link_to 'Lista zaposlenih', employees_path %><br>
  <%= link_to 'Lista firmi', firms_path %> 
</div>